design_config:
  name: "design"
  using_primary: True
  using_secondary: True
  using_harvester: True
  opportunistic: False
  operating_voltage_V: 3.3
  boost_efficiency: 0.8
  frontend_efficiency: 0.8

secondary_config:
  type: "battery"
  capacity_mAh: 10
  nominal_voltage_V: 2.4
  secondary_start_percent: 50.25,
  secondary_max_percent: 50.93,
  secondary_min_percent: 43.25,
  esr_ohm: 0.1
  leakage_constant: 1.E5

primary_config:
  name : "primary"
  #capacity_mAh : 30    #CR927
  #capacity_mAh : 240   #CR2032
  capacity_mAh : 480    #2 CR2032
  #capacity_mAh : 1500  #CR123A
  nominal_voltage_V : 3
  leakage_percent_year : 1

harvest_config:
  type: "solar"
  nominal_voltage: 2.2
  area_cm2: 10.9
  efficiency: 0.17
